### ISSUE TITLE
content-section making

### ISSUE THREAD

**Issue by dreamchach** [git-practice-team8/team-project#2]
-  설명 : 저는 가운데 컨텐츠를 작업.(가운데 컨텐츠는 header 밑에 있는 section을 지칭)
- 가운데 컨텐츠의 class-name을 content-section이라고 명명. 
- 우선, content-section의 html부터 작성

- [x]  make content-section title(html)
- [x]  make content-section description(html)
- [x]  make content-section date(html)
- [x]  make content-section button(html)

**Comment by ulgoon** [comment]
## Description

## Tasks

plz

Dear leader, Set assignees and labels plz

**Comment by syoon0624** [comment]
@dreamchach 
확인했습니다!
