### ISSUE TITLE
역할 분담 및 할일 정리

### ISSUE THREAD

**Issue by syoon0624** [git-practice-team8/team-project#4]
**TODO)**
HTML/CSS 작업
@eun0leee 
1. 헤더 부분 + 섹션 2 부분 숨김 컨텐츠 작업
- [ ] 앵커 태그로 로고 만들기
- [ ] 앵커 태그로 이메일

@dreamchach 
2. 섹션 2 작업
- [ ] make content-section title(html)
- [ ] make content-section description(html)
- [ ] make content-section date(html)
- [ ] make content-section button(html)

@hyerani 
3. 섹션 3 작업 
마지막 섹션의 카운트 부분 구성
- [ ] html 구성
- [ ] css 작업

@0nesan 
4. 동적인 부분 JS 작업
- [ ] 피보나치 카운트 부분 JS 작업
- [ ] 버튼 누를 때 숨김, 드러남 부분 JS 작업
